# Generated by Django 4.1.7 on 2023-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xls_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='xls/')),
                ('sheet_name', models.CharField(blank=True, max_length=40)),
                ('header', models.CharField(blank=True, max_length=40)),
                ('names', models.CharField(blank=True, max_length=40)),
                ('index_col', models.CharField(blank=True, max_length=40)),
                ('usecols', models.CharField(blank=True, max_length=40)),
                ('squeeze', models.CharField(blank=True, max_length=40)),
                ('dtype', models.CharField(blank=True, max_length=40)),
                ('engine', models.CharField(blank=True, max_length=40)),
                ('converters', models.CharField(blank=True, max_length=40)),
                ('true_values', models.CharField(blank=True, max_length=40)),
                ('false_values', models.CharField(blank=True, max_length=40)),
                ('skiprows', models.CharField(blank=True, max_length=40)),
                ('nrows', models.CharField(blank=True, max_length=40)),
                ('na_values', models.CharField(blank=True, max_length=40)),
                ('keep_default_na', models.CharField(blank=True, max_length=40)),
                ('na_filter', models.CharField(blank=True, max_length=40)),
                ('verbose', models.CharField(blank=True, max_length=40)),
                ('parse_dates', models.CharField(blank=True, max_length=40)),
                ('date_parser', models.CharField(blank=True, max_length=40)),
                ('thousands', models.CharField(blank=True, max_length=40)),
                ('decimal', models.CharField(blank=True, max_length=40)),
                ('comment', models.CharField(blank=True, max_length=40)),
                ('skipfooter', models.CharField(blank=True, max_length=40)),
                ('convert_float', models.CharField(blank=True, max_length=40)),
                ('mangle_dupe_cols', models.CharField(blank=True, max_length=40)),
                ('storage_options', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
