# Generated by Django 4.1.5 on 2023-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoDB_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('cluster_address', models.CharField(max_length=70)),
                ('data_base', models.CharField(max_length=20)),
                ('table_mongo', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
