# Generated by Django 4.1.5 on 2023-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='csv/')),
                ('sep', models.CharField(blank=True, max_length=40)),
                ('delimiter', models.CharField(blank=True, max_length=40)),
                ('skipinitialspace', models.CharField(blank=True, max_length=40)),
                ('nrows', models.CharField(blank=True, max_length=40)),
                ('keep_default_na', models.CharField(blank=True, max_length=40)),
                ('verbose', models.CharField(blank=True, max_length=40)),
                ('skip_blank_lines', models.CharField(blank=True, max_length=40)),
                ('infer_datetime_format', models.CharField(blank=True, max_length=40)),
                ('keep_date_col', models.CharField(blank=True, max_length=40)),
                ('cache_dates', models.CharField(blank=True, max_length=40)),
                ('iterator', models.CharField(blank=True, max_length=40)),
                ('thousands', models.CharField(blank=True, max_length=40)),
                ('decimal', models.CharField(blank=True, max_length=40)),
                ('lineterminator', models.CharField(blank=True, max_length=40)),
                ('quoting', models.CharField(blank=True, max_length=40)),
                ('doublequote', models.CharField(blank=True, max_length=40)),
                ('escapechar', models.CharField(blank=True, max_length=40)),
                ('comment', models.CharField(blank=True, max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=40)),
                ('storage_options', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
