# Generated by Django 4.1.7 on 2023-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Json_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='json/')),
                ('orient', models.CharField(blank=True, max_length=40)),
                ('typ', models.CharField(blank=True, max_length=40)),
                ('dtype', models.CharField(blank=True, max_length=40)),
                ('convert_axes', models.CharField(blank=True, max_length=40)),
                ('convert_dates', models.CharField(blank=True, max_length=40)),
                ('keep_default_dates', models.CharField(blank=True, max_length=40)),
                ('numpy', models.CharField(blank=True, max_length=40)),
                ('precise_float', models.CharField(blank=True, max_length=40)),
                ('date_unit', models.CharField(blank=True, max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=40)),
                ('encoding_errors', models.CharField(blank=True, max_length=40)),
                ('lines', models.CharField(blank=True, max_length=40)),
                ('chunksize', models.CharField(blank=True, max_length=40)),
                ('compression', models.CharField(blank=True, max_length=40)),
                ('nrows', models.CharField(blank=True, max_length=40)),
                ('storage_options', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
