# Generated by Django 4.1.5 on 2023-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigQueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='BigQuery/')),
                ('dataset', models.CharField(max_length=40)),
                ('tabela', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
