# Generated by Django 4.1.5 on 2023-03-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bigquery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigquerymodel',
            old_name='tabela',
            new_name='table',
        ),
        migrations.AddField(
            model_name='bigquerymodel',
            name='where',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
